"""Initial migration.

Revision ID: 546421c6c8e3
Revises: 
Create Date: 2024-06-30 10:04:23.946498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546421c6c8e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
